package dev.allan.workoutapp.data

import android.content.Context
import dev.allan.workoutapp.data.db.AppDatabase
import dev.allan.workoutapp.data.db.Exercise
import dev.allan.workoutapp.data.db.ExerciseHit
import dev.allan.workoutapp.data.db.ExerciseTranslation
import kotlinx.serialization.Serializable

/**
 * Searchable index over free-exercise-db (yuhonas, public domain) — the second exercise
 * database next to wger. Bundled slim as assets/fed_index.json (generated by
 * tools/fed-map/generate.py, muscles pre-mapped to wger ids). English-only upstream.
 *
 * Fed exercises stay OUT of the Room DB until the user actually engages with one
 * (opens its detail sheet or adds it to a workout) — then it's imported once as a regular
 * Exercise row with id "fed:<slug>", so notes/links/favorites/sessions all work unchanged.
 */
object FedIndex {

    @Serializable
    data class Entry(
        val id: String,
        val name: String,
        val primary: List<Int> = emptyList(),
        val secondary: List<Int> = emptyList(),
        val cardio: Boolean = false,
        val instructions: String = "",
    )

    const val ID_PREFIX = "fed:"
    private const val IMAGE_BASE =
        "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/"

    @Volatile
    private var entries: List<Entry>? = null

    private fun entries(context: Context): List<Entry> =
        entries ?: synchronized(this) {
            entries ?: kotlinx.serialization.json.Json.decodeFromString<List<Entry>>(
                context.assets.open("fed_index.json").bufferedReader().use { it.readText() }
            ).also { entries = it }
        }

    fun entry(context: Context, slug: String): Entry? =
        entries(context).firstOrNull { it.id == slug }

    fun imageUrl(slug: String, frame: Int = 0): String = "$IMAGE_BASE$slug/$frame.jpg"

    /** Substring search over names (all query tokens must appear), optional muscle filter. */
    fun search(context: Context, query: String, muscleId: Int?): List<ExerciseHit> {
        val tokens = query.trim().lowercase().split(Regex("\\s+")).filter { it.isNotBlank() }
        return entries(context).asSequence()
            .filter { e ->
                tokens.all { e.name.lowercase().contains(it) } &&
                    (muscleId == null || muscleId in e.primary || muscleId in e.secondary)
            }
            .map { e ->
                ExerciseHit(
                    id = ID_PREFIX + e.id,
                    name = e.name.replace('_', ' '),
                    lang = "en",
                    category = null,
                    primaryMuscles = e.primary,
                    secondaryMuscles = e.secondary,
                    isCustom = false,
                    imageUrl = imageUrl(e.id),
                    imagePath = null,
                )
            }
            .sortedBy { it.name }
            .toList()
    }

    /**
     * Import a fed exercise into the DB (no-op when present). Cheap — no downloads here;
     * images ride Coil's disk cache until the exercise is added to a workout.
     */
    suspend fun ensureImported(context: Context, db: AppDatabase, exerciseId: String) {
        if (!exerciseId.startsWith(ID_PREFIX)) return
        if (db.exerciseDao().exercise(exerciseId) != null) return
        val e = entry(context, exerciseId.removePrefix(ID_PREFIX)) ?: return
        db.exerciseDao().insertExercises(
            listOf(
                Exercise(
                    id = exerciseId,
                    category = null,
                    primaryMuscles = e.primary,
                    secondaryMuscles = e.secondary,
                    equipment = emptyList(),
                    imageUrl = imageUrl(e.id),
                    isCustom = false,
                    isCardio = e.cardio,
                    licenseAuthor = "free-exercise-db",
                )
            )
        )
        db.exerciseDao().insertTranslations(
            listOf(
                ExerciseTranslation(
                    exerciseId = exerciseId, lang = "en",
                    name = e.name.replace('_', ' '),
                    description = e.instructions, aliases = emptyList(),
                )
            )
        )
    }
}
