package dev.allan.workoutapp.data

import android.content.Context
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.net.HttpURLConnection
import java.net.URL

/**
 * Movement frames from free-exercise-db (yuhonas, Unlicense/public domain): each mapped
 * exercise has two photos (start/end position) that the gallery plays as a 2-frame
 * animation. assets/fed_map.json (generated by tools/fed-map/generate.py) maps wger ids
 * to fed slugs — exact-name matches only, a wrong movement is worse than none.
 * Frames download on demand and are kept offline next to the other exercise media.
 */
object FedMedia {

    /** exercise_media/ filename prefix — MediaStore.sweep must not touch these. */
    const val FILE_PREFIX = "fed_"

    private const val BASE =
        "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/"
    private const val MAX_BYTES = 5_000_000

    @Volatile
    private var map: Map<String, String>? = null

    private fun map(context: Context): Map<String, String> =
        map ?: synchronized(this) {
            map ?: kotlinx.serialization.json.Json.decodeFromString<Map<String, String>>(
                context.assets.open("fed_map.json").bufferedReader().use { it.readText() }
            ).also { map = it }
        }

    fun slugFor(context: Context, exerciseId: String): String? = map(context)[exerciseId]

    private fun frameFile(context: Context, slug: String, index: Int): File =
        File(File(context.filesDir, "exercise_media"), "$FILE_PREFIX${slug}_$index.jpg")

    /** Both frame paths when already downloaded, else null. */
    fun localFrames(context: Context, exerciseId: String): List<String>? {
        val slug = slugFor(context, exerciseId) ?: return null
        val files = (0..1).map { frameFile(context, slug, it) }
        return files.map { it.absolutePath }.takeIf { files.all { f -> f.exists() } }
    }

    /** Download both frames (no-op when present). Null on any failure — all or nothing. */
    suspend fun fetchFrames(context: Context, exerciseId: String): List<String>? =
        withContext(Dispatchers.IO) {
            val slug = slugFor(context, exerciseId) ?: return@withContext null
            localFrames(context, exerciseId)?.let { return@withContext it }
            File(context.filesDir, "exercise_media").mkdirs()
            val files = (0..1).map { frameFile(context, slug, it) }
            runCatching {
                files.forEachIndexed { i, file ->
                    if (!file.exists()) {
                        val bytes = download("$BASE$slug/$i.jpg") ?: error("download failed")
                        file.writeBytes(bytes)
                    }
                }
                files.map { it.absolutePath }
            }.getOrElse {
                files.forEach { it.delete() }
                null
            }
        }

    private fun download(url: String): ByteArray? {
        val conn = URL(url).openConnection() as HttpURLConnection
        conn.connectTimeout = 15000
        conn.readTimeout = 30000
        conn.instanceFollowRedirects = true
        return try {
            if (conn.responseCode != 200) return null
            conn.inputStream.use { it.readBytes().takeIf { b -> b.size <= MAX_BYTES } }
        } finally {
            conn.disconnect()
        }
    }
}
