#!/usr/bin/env python3
"""Build app/src/main/assets/pt_aliases.json from the hand-written part*.json tables.

Keys in part*.json are exact English exercise names from the wger snapshot;
values are pt-BR names (generated by Claude, reviewed by hand as needed).
The output maps wger exercise id -> pt name, only for exercises that lack a
pt translation in the snapshot. Warns about keys that match nothing (typos)
so the tables stay in sync with snapshot refreshes.
"""

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SNAPSHOT = HERE.parents[1] / "app/src/main/assets/wger_snapshot.json"
OUT = HERE.parents[1] / "app/src/main/assets/pt_aliases.json"


def main():
    table = {}
    for part in sorted(HERE.glob("part*.json")):
        entries = json.loads(part.read_text(encoding="utf-8"))
        dupes = table.keys() & entries.keys()
        if dupes:
            print(f"note: {part.name} re-defines {len(dupes)} keys (last wins)")
        table.update(entries)

    snap = json.loads(SNAPSHOT.read_text(encoding="utf-8"))
    by_en_name = {}
    missing_pt = set()
    for ex in snap["exercises"]:
        en = ex["translations"]["en"]["name"]
        by_en_name.setdefault(en, ex["id"])
        if "pt" not in ex["translations"]:
            missing_pt.add(ex["id"])

    aliases = {}
    unmatched = []
    for en_name, pt_name in table.items():
        ex_id = by_en_name.get(en_name)
        if ex_id is None:
            unmatched.append(en_name)
        elif ex_id in missing_pt:
            aliases[str(ex_id)] = pt_name

    OUT.write_text(
        json.dumps({"schema": 1, "aliases": aliases}, ensure_ascii=False, indent=0),
        encoding="utf-8",
    )
    still_missing = len(missing_pt) - len(aliases)
    print(f"wrote {OUT.name}: {len(aliases)} pt names "
          f"({len(missing_pt)} lacked pt; {still_missing} still untranslated)")
    if unmatched:
        print(f"WARNING: {len(unmatched)} table keys match no snapshot exercise:")
        for name in unmatched:
            print(f"  - {name!r}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
