package dev.allan.workoutapp.ui.common

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.ColorFilter
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import coil.ImageLoader
import coil.compose.AsyncImage
import coil.request.ImageRequest
import dev.allan.workoutapp.R
import dev.allan.workoutapp.data.MuscleMap
import dev.allan.workoutapp.data.Settings
import kotlinx.coroutines.launch

/**
 * Muscle map. Renders a flat vector front + back body (ported from
 * react-native-body-highlighter, MIT — see tools/body-highlighter/) and overlays each targeted
 * muscle's region, tinted blue by training load — deeper blue = more exercises hitting it, so
 * over/under-trained muscles read at a glance. Assets bundled in assets/body/
 * (male: front.svg/back.svg/muscle-<wgerId>.svg; female: same names with a -f suffix),
 * regenerated by tools/body-highlighter/convert.py. The male/female choice is a persisted
 * setting toggled by the "Switch model" button on the legend row.
 */
@Composable
fun BodyMap(
    load: Map<Int, Float>,
    modifier: Modifier = Modifier,
    title: String? = null,
) {
    val context = LocalContext.current
    val loader = remember { AppImageLoader.get(context) }
    val female by Settings.bodyFemale(context).collectAsState(initial = false)
    val scope = rememberCoroutineScope()
    // Per-view aspect ratios come from the library wrappers' viewBoxes.
    val suffix = if (female) "-f" else ""
    val frontAspect = if (female) 734f / 1538f else 724f / 1448f
    val backAspect = if (female) 774f / 1448f else 724f / 1448f
    Column(modifier) {
        if (title != null) {
            Text(
                title,
                style = MaterialTheme.typography.labelMedium,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
                modifier = Modifier.padding(bottom = 4.dp),
            )
        }
        Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
            BodyView("body/front$suffix.svg", suffix, frontAspect, MuscleMap.FRONT_IDS, load, loader, Modifier.weight(1f))
            BodyView("body/back$suffix.svg", suffix, backAspect, MuscleMap.BACK_IDS, load, loader, Modifier.weight(1f))
        }
        Legend(onSwitchModel = { scope.launch { Settings.setBodyFemale(context, !female) } })
    }
}

@Composable
private fun BodyView(
    baseAsset: String,
    suffix: String,
    aspect: Float,
    ids: Set<Int>,
    load: Map<Int, Float>,
    loader: ImageLoader,
    modifier: Modifier,
) {
    val context = LocalContext.current
    // Base and overlays share the same viewBox per view; FillBounds keeps them
    // registered on each other.
    Box(modifier.fillMaxWidth().aspectRatio(aspect)) {
        AsyncImage(
            model = ImageRequest.Builder(context).data("file:///android_asset/$baseAsset").build(),
            imageLoader = loader,
            contentDescription = null,
            contentScale = ContentScale.FillBounds,
            modifier = Modifier.fillMaxWidth().aspectRatio(aspect),
        )
        ids.forEach { id ->
            val l = load[id] ?: 0f
            if (l <= 0f) return@forEach
            AsyncImage(
                model = ImageRequest.Builder(context)
                    .data("file:///android_asset/body/muscle-$id$suffix.svg").build(),
                imageLoader = loader,
                contentDescription = null,
                contentScale = ContentScale.FillBounds,
                colorFilter = ColorFilter.tint(loadColor(l)),
                modifier = Modifier.fillMaxWidth().aspectRatio(aspect),
            )
        }
    }
}

/** Legend: colored squares mapping shade -> number of exercises hitting the muscle. */
@Composable
private fun Legend(onSwitchModel: () -> Unit) {
    val steps = listOf(
        1f to "1",
        2f to "2",
        3f to "3",
        4f to "4+",
    )
    Column(Modifier.padding(top = 8.dp)) {
        Text(
            androidx.compose.ui.res.stringResource(R.string.muscle_legend_header),
            style = MaterialTheme.typography.labelSmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
        )
        Row(
            Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(10.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            steps.forEach { (load, label) ->
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Box(
                        Modifier
                            .size(14.dp)
                            .clip(RoundedCornerShape(3.dp))
                            .background(loadColor(load)),
                    )
                    Text(
                        " $label",
                        style = MaterialTheme.typography.labelSmall,
                    )
                }
            }
            Text(
                androidx.compose.ui.res.stringResource(R.string.muscle_legend_unit),
                style = MaterialTheme.typography.labelSmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
                modifier = Modifier.weight(1f),
            )
            TextButton(onClick = onSwitchModel) {
                Text(
                    androidx.compose.ui.res.stringResource(R.string.switch_model),
                    style = MaterialTheme.typography.labelSmall,
                )
            }
        }
    }
}

/**
 * Light blue at load ~1 up to deep blue at load >=4 — the over/under-trained signal.
 * Blue matches the app's icon/accent language (Allan 2026-07-11).
 */
private fun loadColor(load: Float): Color {
    val light = Color(0xFF90CAF9)
    val deep = Color(0xFF1565C0)
    val t = ((load - 1f) / 3f).coerceIn(0f, 1f)
    return androidx.compose.ui.graphics.lerp(light, deep, t)
}
