package dev.allan.workoutapp.ui.common

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.ColorFilter
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.foundation.layout.heightIn
import androidx.compose.material3.OutlinedButton
import coil.ImageLoader
import coil.compose.AsyncImage
import coil.request.ImageRequest
import dev.allan.workoutapp.R
import dev.allan.workoutapp.data.MuscleMap
import dev.allan.workoutapp.data.MuscleNames
import kotlin.math.roundToInt
import dev.allan.workoutapp.data.Settings
import kotlinx.coroutines.launch

/** All body viewBoxes are normalized to this width:height by convert.py — keep in sync. */
private const val BODY_ASPECT = 0.5f

/**
 * Muscle map. Renders a flat vector front + back body (ported from
 * react-native-body-highlighter, MIT — see tools/body-highlighter/) and overlays each targeted
 * muscle's region, tinted blue by training load — deeper blue = more exercises hitting it, so
 * over/under-trained muscles read at a glance. Assets bundled in assets/body/
 * (male: front.svg/back.svg/muscle-<wgerId>.svg; female: same names with a -f suffix),
 * regenerated by tools/body-highlighter/convert.py. The male/female choice is a persisted
 * setting toggled by the "Switch model" button on the legend row.
 */
@Composable
fun BodyMap(
    load: Map<Int, Float>,
    modifier: Modifier = Modifier,
    title: String? = null,
) {
    val context = LocalContext.current
    val loader = remember { AppImageLoader.get(context) }
    val female by Settings.bodyFemale(context).collectAsState(initial = false)
    val scope = rememberCoroutineScope()
    val suffix = if (female) "-f" else ""
    // Shading is relative to the heaviest muscle: the load is in working sets now, so the
    // absolute 1..4 scale of the exercise-count days would saturate on any real workout.
    val max = load.values.maxOrNull()?.takeIf { it > 0f } ?: 1f
    val db = remember { (context.applicationContext as dev.allan.workoutapp.WorkoutApp).db }
    val muscles by remember { db.exerciseDao().muscles() }.collectAsState(initial = emptyList())
    val lang = androidx.compose.ui.platform.LocalConfiguration.current.locales[0].language
    Column(modifier) {
        if (title != null) {
            Text(
                title,
                style = MaterialTheme.typography.labelMedium,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
                modifier = Modifier.padding(bottom = 4.dp),
            )
        }
        // The ranking in words, so "targets quads the most" can be checked against the
        // numbers instead of a shade (Allan, 29/08).
        val top = MuscleMap.topShares(load, 3)
        if (top.isNotEmpty() && muscles.isNotEmpty()) {
            val byId = muscles.associateBy { it.id }
            Text(
                top.joinToString(" · ") { (id, share) ->
                    val name = byId[id]?.let { MuscleNames.display(it.nameEn, lang) } ?: "#$id"
                    "$name ${(share * 100).roundToInt()}%"
                },
                style = MaterialTheme.typography.bodySmall,
                modifier = Modifier.padding(bottom = 6.dp),
            )
        }
        Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
            BodyView("body/front$suffix.svg", suffix, BODY_ASPECT, MuscleMap.FRONT_IDS, load, max, loader, Modifier.weight(1f))
            BodyView("body/back$suffix.svg", suffix, BODY_ASPECT, MuscleMap.BACK_IDS, load, max, loader, Modifier.weight(1f))
        }
        Legend(max, onSwitchModel = { scope.launch { Settings.setBodyFemale(context, !female) } })
    }
}

@Composable
private fun BodyView(
    baseAsset: String,
    suffix: String,
    aspect: Float,
    ids: Set<Int>,
    load: Map<Int, Float>,
    max: Float,
    loader: ImageLoader,
    modifier: Modifier,
) {
    val context = LocalContext.current
    // Base and overlays share the same viewBox per view; FillBounds keeps them
    // registered on each other.
    Box(modifier.fillMaxWidth().aspectRatio(aspect)) {
        AsyncImage(
            model = ImageRequest.Builder(context).data("file:///android_asset/$baseAsset").build(),
            imageLoader = loader,
            contentDescription = null,
            contentScale = ContentScale.FillBounds,
            modifier = Modifier.fillMaxWidth().aspectRatio(aspect),
        )
        ids.forEach { id ->
            val l = load[id] ?: 0f
            if (l <= 0f) return@forEach
            AsyncImage(
                model = ImageRequest.Builder(context)
                    .data("file:///android_asset/body/muscle-$id$suffix.svg").build(),
                imageLoader = loader,
                contentDescription = null,
                contentScale = ContentScale.FillBounds,
                colorFilter = ColorFilter.tint(loadColor(l / max)),
                modifier = Modifier.fillMaxWidth().aspectRatio(aspect),
            )
        }
    }
}

/** Legend: colored squares mapping shade -> working sets on the muscle (quarters of the max). */
@Composable
private fun Legend(max: Float, onSwitchModel: () -> Unit) {
    val steps = listOf(0.25f, 0.5f, 0.75f, 1f).map { t -> t to fmtSets(max * t) }
    Column(Modifier.padding(top = 8.dp)) {
        Text(
            androidx.compose.ui.res.stringResource(R.string.muscle_legend_header),
            style = MaterialTheme.typography.labelSmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
        )
        Row(
            Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(10.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            steps.forEach { (load, label) ->
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Box(
                        Modifier
                            .size(14.dp)
                            .clip(RoundedCornerShape(3.dp))
                            .background(loadColor(load)),
                    )
                    Text(
                        " $label",
                        style = MaterialTheme.typography.labelSmall,
                    )
                }
            }
            Text(
                androidx.compose.ui.res.stringResource(R.string.muscle_legend_unit),
                style = MaterialTheme.typography.labelSmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
                modifier = Modifier.weight(1f),
            )
            OutlinedButton(
                onClick = onSwitchModel,
                contentPadding = androidx.compose.foundation.layout.PaddingValues(horizontal = 10.dp, vertical = 2.dp),
                modifier = Modifier.heightIn(min = 28.dp),
            ) {
                Text(
                    androidx.compose.ui.res.stringResource(R.string.switch_model),
                    style = MaterialTheme.typography.labelSmall,
                )
            }
        }
    }
}

/** "3" or "1.5" — half sets exist because a secondary muscle counts half. */
private fun fmtSets(v: Float): String =
    if (v == v.roundToInt().toFloat()) v.roundToInt().toString() else String.format(java.util.Locale.ROOT, "%.1f", v)

/**
 * Light blue for the lightest-loaded muscle up to deep blue for the heaviest ([t] = share of
 * the max) — the over/under-trained signal. Blue matches the app's icon/accent language
 * (Allan 2026-07-11).
 */
private fun loadColor(t: Float): Color {
    val light = Color(0xFF90CAF9)
    val deep = Color(0xFF1565C0)
    return androidx.compose.ui.graphics.lerp(light, deep, t.coerceIn(0f, 1f))
}
