package dev.allan.workoutapp.ui.common

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.aspectRatio
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.ColorFilter
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import coil.ImageLoader
import coil.compose.AsyncImage
import coil.decode.SvgDecoder
import coil.request.ImageRequest
import dev.allan.workoutapp.R
import dev.allan.workoutapp.data.MuscleMap

/**
 * Muscle map. Renders a flat vector front + back body (ported from
 * react-native-body-highlighter, MIT — see tools/body-highlighter/) and overlays each targeted
 * muscle's region, tinted blue by training load — deeper blue = more exercises hitting it, so
 * over/under-trained muscles read at a glance. Assets bundled in assets/body/
 * (base: front.svg/back.svg; overlays: muscle-<wgerId>.svg), regenerated by
 * tools/body-highlighter/convert.py.
 */
@Composable
fun BodyMap(
    load: Map<Int, Float>,
    modifier: Modifier = Modifier,
    title: String? = null,
) {
    val context = LocalContext.current
    val loader = remember { ImageLoader.Builder(context).components { add(SvgDecoder.Factory()) }.build() }
    Column(modifier) {
        if (title != null) {
            Text(
                title,
                style = MaterialTheme.typography.labelMedium,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
                modifier = Modifier.padding(bottom = 4.dp),
            )
        }
        Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
            BodyView("body/front.svg", MuscleMap.FRONT_IDS, load, loader, Modifier.weight(1f))
            BodyView("body/back.svg", MuscleMap.BACK_IDS, load, loader, Modifier.weight(1f))
        }
        Legend()
    }
}

@Composable
private fun BodyView(
    baseAsset: String,
    ids: Set<Int>,
    load: Map<Int, Float>,
    loader: ImageLoader,
    modifier: Modifier,
) {
    val context = LocalContext.current
    // Base and overlays share the same viewBox (724x1448 per view); FillBounds keeps them
    // registered on each other.
    Box(modifier.fillMaxWidth().aspectRatio(724f / 1448f)) {
        AsyncImage(
            model = ImageRequest.Builder(context).data("file:///android_asset/$baseAsset").build(),
            imageLoader = loader,
            contentDescription = null,
            contentScale = ContentScale.FillBounds,
            modifier = Modifier.fillMaxWidth().aspectRatio(724f / 1448f),
        )
        ids.forEach { id ->
            val l = load[id] ?: 0f
            if (l <= 0f) return@forEach
            AsyncImage(
                model = ImageRequest.Builder(context)
                    .data("file:///android_asset/body/muscle-$id.svg").build(),
                imageLoader = loader,
                contentDescription = null,
                contentScale = ContentScale.FillBounds,
                colorFilter = ColorFilter.tint(loadColor(l)),
                modifier = Modifier.fillMaxWidth().aspectRatio(724f / 1448f),
            )
        }
    }
}

/** Legend: colored squares mapping shade -> number of exercises hitting the muscle. */
@Composable
private fun Legend() {
    val steps = listOf(
        1f to "1",
        2f to "2",
        3f to "3",
        4f to "4+",
    )
    Column(Modifier.padding(top = 8.dp)) {
        Text(
            androidx.compose.ui.res.stringResource(R.string.muscle_legend_header),
            style = MaterialTheme.typography.labelSmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
        )
        Row(
            Modifier.padding(top = 4.dp),
            horizontalArrangement = Arrangement.spacedBy(10.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            steps.forEach { (load, label) ->
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Box(
                        Modifier
                            .size(14.dp)
                            .clip(RoundedCornerShape(3.dp))
                            .background(loadColor(load)),
                    )
                    Text(
                        " $label",
                        style = MaterialTheme.typography.labelSmall,
                    )
                }
            }
            Text(
                androidx.compose.ui.res.stringResource(R.string.muscle_legend_unit),
                style = MaterialTheme.typography.labelSmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )
        }
    }
}

/**
 * Light blue at load ~1 up to deep blue at load >=4 — the over/under-trained signal.
 * Blue matches the app's icon/accent language (Allan 2026-07-11).
 */
private fun loadColor(load: Float): Color {
    val light = Color(0xFF90CAF9)
    val deep = Color(0xFF1565C0)
    val t = ((load - 1f) / 3f).coerceIn(0f, 1f)
    return androidx.compose.ui.graphics.lerp(light, deep, t)
}
